name: Docker Image CI

on: [push]

jobs:

  ElasticSearch:

    runs-on: ubuntu-latest

    steps:
    - name: Setup ElasticSearch
    - uses: getong/elasticsearch-action@v1
      with:
        # Version of elasticsearch to use
        elasticsearch version: # optional, default is latest
        # The port of host
        host port: # optional, default is 9200
        # The port of container
        container port: # optional, default is 9200
        # the discovery.type envionment
        discovery type: # optional, default is single-node
      run: mvn -v #docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  ElasticSearch0:

    runs-on: ubuntu-latest

    steps:
    - name: Setup ElasticSearch 0
    - uses: getong/elasticsearch-action@v1
    - with:
        # Version of elasticsearch to use
        elasticsearch version: # optional, default is latest
        # The port of host
        host port: # optional, default is 9200
        # The port of container
        container port: # optional, default is 9200
        # the discovery.type envionment
        discovery type: # optional, default is single-node
      run: mvn -v #docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Test the Docker image through mvn
    - uses: actions/checkout@v2
      run: mvn -v #docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  ElasticSearch1:

    runs-on: ubuntu-latest

    steps:
    - uses: getong/elasticsearch-action@v1
    - name: Run the Docker image ElasticSearch1
      run: docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.16

    # - uses: getong/elasticsearch-action@v1
    # - name: Pull the Docker image ElasticSearch1
    # - run: docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.16

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #   - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


