name: Docker elasticsearch-action@v1 Image CI

on: [push]

jobs:      

  ElasticSearch_instance:

    runs-on: ubuntu-latest

    steps:
    - name: actions/checkout v2
      uses: actions/checkout@v2

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '7.17.6'
        host port: 9200
        container port: 9200
        host node port: 9300
        node port: 9300
        discovery type: 'single-node'

    - name: ESMainTest
      run: |
        mvn test -Dtest=ESMainTest test
