name: Docker Image CI

on: [push]

jobs:

  ElasticSearch:

    runs-on: ubuntu-latest

    steps:
    - name: Setup ElasticSearch
    - uses: getong/elasticsearch-action@v1

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Test the Docker image through mvn
    - uses: actions/checkout@v1
      run: mvn -v #docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


